// Code generated by "stringer -type=Operation -trimprefix=Op"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpCaret-1]
	_ = x[OpDollar-2]
	_ = x[OpLiteral-3]
	_ = x[OpQuote-4]
	_ = x[OpEscape-5]
	_ = x[OpEscapeMeta-6]
	_ = x[OpEscapeOctal-7]
	_ = x[OpEscapeHex-8]
	_ = x[OpEscapeHexFull-9]
	_ = x[OpEscapeUni-10]
	_ = x[OpEscapeUniFull-11]
	_ = x[OpCharClass-12]
	_ = x[OpNegCharClass-13]
	_ = x[OpCharRange-14]
	_ = x[OpPosixClass-15]
	_ = x[OpRepeat-16]
	_ = x[OpCapture-17]
	_ = x[OpNamedCapture-18]
	_ = x[OpGroup-19]
	_ = x[OpGroupWithFlags-20]
	_ = x[OpFlagOnlyGroup-21]
	_ = x[OpConcat-22]
	_ = x[OpDot-23]
	_ = x[OpPerlCharClass-24]
	_ = x[OpNegPerlCharClass-25]
	_ = x[OpNamedCharClass-26]
	_ = x[OpNegNamedCharClass-27]
	_ = x[OpUniCharClass-28]
	_ = x[OpNegUniCharClass-29]
	_ = x[OpAlt-30]
	_ = x[OpStar-31]
	_ = x[OpPlus-32]
	_ = x[OpQuestion-33]
	_ = x[OpNonGreedy-34]
}

const _Operation_name = "NoneCaretDollarLiteralQuoteEscapeEscapeMetaEscapeOctalEscapeHexEscapeHexFullEscapeUniEscapeUniFullCharClassNegCharClassCharRangePosixClassRepeatCaptureNamedCaptureGroupGroupWithFlagsFlagOnlyGroupConcatDotPerlCharClassNegPerlCharClassNamedCharClassNegNamedCharClassUniCharClassNegUniCharClassAltStarPlusQuestionNonGreedy"

var _Operation_index = [...]uint16{0, 4, 9, 15, 22, 27, 33, 43, 54, 63, 76, 85, 98, 107, 119, 128, 138, 144, 151, 163, 168, 182, 195, 201, 204, 217, 233, 247, 264, 276, 291, 294, 298, 302, 310, 319}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
