// Code generated by "stringer -type=Operation -trimprefix=Op"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpConcat-1]
	_ = x[OpDot-2]
	_ = x[OpAlt-3]
	_ = x[OpStar-4]
	_ = x[OpPlus-5]
	_ = x[OpQuestion-6]
	_ = x[OpNonGreedy-7]
	_ = x[OpPossessive-8]
	_ = x[OpCaret-9]
	_ = x[OpDollar-10]
	_ = x[OpLiteral-11]
	_ = x[OpChar-12]
	_ = x[OpString-13]
	_ = x[OpQuote-14]
	_ = x[OpEscape-15]
	_ = x[OpEscapeMeta-16]
	_ = x[OpEscapeOctal-17]
	_ = x[OpEscapeHex-18]
	_ = x[OpEscapeHexFull-19]
	_ = x[OpEscapeUni-20]
	_ = x[OpEscapeUniFull-21]
	_ = x[OpCharClass-22]
	_ = x[OpNegCharClass-23]
	_ = x[OpCharRange-24]
	_ = x[OpPosixClass-25]
	_ = x[OpRepeat-26]
	_ = x[OpCapture-27]
	_ = x[OpNamedCapture-28]
	_ = x[OpGroup-29]
	_ = x[OpGroupWithFlags-30]
	_ = x[OpFlagOnlyGroup-31]
	_ = x[OpNone2-32]
}

const _Operation_name = "NoneConcatDotAltStarPlusQuestionNonGreedyPossessiveCaretDollarLiteralCharStringQuoteEscapeEscapeMetaEscapeOctalEscapeHexEscapeHexFullEscapeUniEscapeUniFullCharClassNegCharClassCharRangePosixClassRepeatCaptureNamedCaptureGroupGroupWithFlagsFlagOnlyGroupNone2"

var _Operation_index = [...]uint16{0, 4, 10, 13, 16, 20, 24, 32, 41, 51, 56, 62, 69, 73, 79, 84, 90, 100, 111, 120, 133, 142, 155, 164, 176, 185, 195, 201, 208, 220, 225, 239, 252, 257}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
