// Code generated by "stringer -type=Operation -trimprefix=Op"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpConcat-1]
	_ = x[OpDot-2]
	_ = x[OpAlt-3]
	_ = x[OpStar-4]
	_ = x[OpPlus-5]
	_ = x[OpQuestion-6]
	_ = x[OpNonGreedy-7]
	_ = x[OpCaret-8]
	_ = x[OpDollar-9]
	_ = x[OpLiteral-10]
	_ = x[OpQuote-11]
	_ = x[OpEscape-12]
	_ = x[OpEscapeMeta-13]
	_ = x[OpEscapeOctal-14]
	_ = x[OpEscapeHex-15]
	_ = x[OpEscapeHexFull-16]
	_ = x[OpEscapeUni-17]
	_ = x[OpEscapeUniFull-18]
	_ = x[OpCharClass-19]
	_ = x[OpNegCharClass-20]
	_ = x[OpCharRange-21]
	_ = x[OpPosixClass-22]
	_ = x[OpRepeat-23]
	_ = x[OpCapture-24]
	_ = x[OpNamedCapture-25]
	_ = x[OpGroup-26]
	_ = x[OpGroupWithFlags-27]
	_ = x[OpFlagOnlyGroup-28]
	_ = x[OpNone2-29]
}

const _Operation_name = "NoneConcatDotAltStarPlusQuestionNonGreedyCaretDollarLiteralQuoteEscapeEscapeMetaEscapeOctalEscapeHexEscapeHexFullEscapeUniEscapeUniFullCharClassNegCharClassCharRangePosixClassRepeatCaptureNamedCaptureGroupGroupWithFlagsFlagOnlyGroupNone2"

var _Operation_index = [...]uint8{0, 4, 10, 13, 16, 20, 24, 32, 41, 46, 52, 59, 64, 70, 80, 91, 100, 113, 122, 135, 144, 156, 165, 175, 181, 188, 200, 205, 219, 232, 237}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
